name: 'Build issue dependencies graph'
author: 'Maksim Lobanov'
description: 'Update epic issue with mermaid diagram that contains dependencies between all issues included to epic'
inputs:
  root-issue-url:
    description: 'Url of the root issue'
    required: true
  section-title:
    description: 'Title of markdown section where mermaid chart should be placed'
    required: true
  github-token:
    description: 'GitHub API Token with read and write access to root issue and read access to all issues in the tasklist'
    required: true
  include-legend:
    description: 'Set this option to include legend to mermaid diagram'
    required: false
    default: 'false'
  include-finish-node:
    description: 'Set this option to include finish node to mermaid diagram'
    required: false
    default: 'false'
  dry-run:
    description: 'Set this option to not update root issue with updated mermaid diagram and only print new diagram to output'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'